Some new things!  Don't trust csv-from-obj though...

diff --git a/csv-from-obj b/csv-from-obj
--- a/csv-from-obj
+++ b/csv-from-obj
@@ -1,102 +1,49 @@
 #!/bin/bash
 
 # Given an obj file, samples it to get it as a high-quality CSV.
+# Sampling is done using the BuiltViewLibrary strategy
 
-export readonly name=$( basename $0 )
+export readonly name=$(basename $0)
 
-source $( type -p comma-application-util ) || (error "comma not installed")
-function errcho { (>&2 echo "$name: $1") }
-function error
-{
-    errcho "error: $1"
-    exit 1
-}
-# # Half-hearted attempt, never finished
-# function sample() {
-#   local group=$1
-#   local gLines=$2
-#   local lines=$3
-#   local density=$4
-#   local OBJ=$5
-#   local id=$6
-#   local verbose=$7
-#
-#   set=$(echo "$gLines" | grep $group -A 1 | tr '\n' ':' | sed 's/:$/\n/')
-#   start=$(echo $set | cut -d: -f1)
-#   label=$(echo $set | cut -d: -f2)
-#   n=$(expr $lines - $start)
-#
-#   e=$(echo $set | cut -d: -f3)
-#   if [[ $e ]]
-#   then
-#     end=$(expr $e - 1)
-#     d=$(expr $end - $start)
-#     cat verts.csv <(cat $OBJ | tail -$n | head -$d ) > $label.obj
-#   else
-#     cat verts.csv <(cat $OBJ | tail -$n) > $label.obj
-#   fi
-#   cloudcompare.CloudCompare -SILENT -NO_TIMESTAMP -C_EXPORT_FMT LAS -O $label.obj -SAMPLE_MESH DENSITY $density >/dev/null 2>/dev/null
-#   cat ${label}_SAMPLED_POINTS.las | las-to-csv points | csv-shuffle -f=x,y,z -o=x,y,z | csv-paste "-" "value=$id"
-#   [[ $verbose ]] && echo -n "." >&2
-# }
-
-function convert() {
-  OBJ=$1
-  density=$2
-
-	cat $OBJ | grep "^v" > verts.csv
-
-	gLines=$(cat $OBJ | grep "^g" -n | sed 's/:g//' | sed -r 's/\s/:/g')
-	lines=$(cat $OBJ | wc -l)
-
-	id=$(cat $OBJ | grep "^g" -n | wc -l)
-
-  # export -f sample
-  # echo "$gLines" | parallel -n1 -j8 sample {} $gLines $lines $density $OBJ {= '$_=total_jobs()-$job->seq()+1' =} $verbose |
-	for group in `echo "$gLines"`
-	do
-    [[ $verbose ]] && echo "Processing $group ($id)..." >&2
-
-		set=$(echo "$gLines" | grep $group -A 1 | tr '\n' ':' | sed 's/:$/\n/')
-    [[ $verbose ]] && echo "Set: $set" >&2
-		start=$(echo $set | cut -d: -f1)
-		label=$(echo $set | cut -d: -f2)
-		n=$(expr $lines - $start)
-
-		e=$(echo $set | cut -d: -f4)
-		if [[ $e ]]
-		then
-			end=$(expr $e - 1)
-			d=$(expr $end - $start)
-			cat verts.csv <(cat $OBJ | tail -$n | head -$d ) > $label.obj
-		else
-			cat verts.csv <(cat $OBJ | tail -$n) > $label.obj
-		fi
-		cloudcompare.CloudCompare -SILENT -NO_TIMESTAMP -C_EXPORT_FMT LAS -O $label.obj -SAMPLE_MESH DENSITY $density >/dev/null 2>/dev/null
-    cat ${label}_SAMPLED_POINTS.las | las-to-csv points | csv-shuffle -f=x,y,z -o=x,y,z | csv-paste "-" "value=$id"
-    [[ $verbose ]] && echo "Done!" >&2
-		id=$(expr $id - 1)
-	done |
-  if [[ $show ]]
-  then
-    tee >(view-points "-;format=3d,ui;fields=x,y,z,id" --size=20000000 "$pc;binary=$bin;fields=$fields")
-  else
-    cat
-  fi
+source $(type -p comma-application-util) || (error "comma not installed")
+function errcho() { (echo >&2 "$name: $1"); }
+function error() {
+	errcho "error: $1"
+	exit 1
 }
 
-function option-description
-{
-    cat <<eof
---density=[<quality>]; default=20000; Density of mesh point cloud sampling
+function go() {
+	local INFILE=$1
+	local density=$2
+
+	[[ $verbose ]] && echo "Density: $density" >&2
+
+	obj-to-tri $INFILE | triangle-area |
+		csv-eval --binary=ui,9d,d --fields=,,,,,,,,,,area "npts=area*$density + 0.5" --output-format=ui |
+		csv-paste "-;binary=ui,9d,d,ui,2d" "line-number;binary=ui" |
+		csv-eval --binary=ui,9d,d,ui,2d,ui --fields=i,,,,,,,,,,,,,l "i=l" |
+		csv-shuffle -b=ui,9d,d,ui,2d,ui -f=i,fx,fy,fz,sx,sy,sz,tx,ty,tz,a,n -o=i,fx,fy,fz,sx,sy,sz,tx,ty,tz,a,n |
+		csv-replicate |
+		# We now have one line per new point - all we have to do is compute the new coordinates using rand...
+		csv-random |
+		csv-eval --binary=ui,9d,d,ui,2d --fields=,fx,fy,fz,sx,sy,sz,tx,ty,tz,,,a,b \
+			"sa=sqrt(a);sb=sqrt(b);\
+		x=(1-sa)*fx + (sa*(1-b)) * sx + b * sa * tx;\
+		y=(1-sa)*fy + (sa*(1-b)) * sy + b * sa * ty;\
+		z=(1-sa)*fz + (sa*(1-b)) * sz + b * sa * tz" --output-format 3d --output-fields=x,y,z |
+		csv-shuffle -b=ui,9d,d,ui,2d,3d -f=id,,,,,,,,,,a,n,r1,r2,x,y,z -o=id,x,y,z,a
+}
+
+function option-description() {
+	cat <<eof
+--density=[<quality>]; default=3; Density of mesh point cloud sampling in points per square metre (approximate)
 --verbose, -v; Output progress to stderr
 --show, -s; Display cloud when finished
 eof
 }
 
-function usage
-{
-    cat <<eof
+function usage() {
+	cat <<eof
 
 $name uses tree and LiDAR definitions to procedurally generate a point cloud
 as if the defined sensor had scanned a set of random trees of the given species.
@@ -106,10 +53,10 @@ Also creates a temporary directory to store intermediate files.
 usage: $name obj [options]
 
 options:
-$( option-description  | sed 's/^/    /g' )
+$(option-description | sed 's/^/    /g')
 
 eof
-    exit 1
+	exit 1
 
 }
 
@@ -119,25 +66,23 @@ if [ "$1" = "-parallel" ]; then
 	exit $?
 fi
 
+if (($(comma_options_has --help $@) || $(comma_options_has -h $@))); then usage; fi
+options=$(option-description | comma-options-to-name-value "$@") || error "invalid command line options"
+comma_path_value_to_var --prefix="options" <<<"$options"
+eval "$(option-description | comma-options-to-name-value "$@" | comma_path_value_mangle)"
 
-if (( $( comma_options_has --help $@ ) || $( comma_options_has -h $@ ) )) ; then usage ; fi
-options=$( option-description | comma-options-to-name-value "$@" ) || error "invalid command line options"
-comma_path_value_to_var --prefix="options" <<< "$options"
-eval "$( option-description | comma-options-to-name-value "$@" | comma_path_value_mangle )"
-
-(( $( comma_options_has --verbose "$@" ) )) && export readonly verbose=true
-(( $( comma_options_has --force "$@" ) )) && export readonly recompute=true
+(($(comma_options_has --verbose "$@"))) && export readonly verbose=true
+(($(comma_options_has --force "$@"))) && export readonly recompute=true
 
 set -e # Kill if anything errors out; we don't want it to run everything on bad datasets
 
-wherewasi=`pwd`
-fullfilename=`readlink -f $1`
+wherewasi=$(pwd)
+fullfilename=$(readlink -f $1)
 # export TEMPDIR=`mktemp -d`
-export TEMPDIR="temp_thingos"
-mkdir $TEMPDIR
+export TEMPDIR=$(mktemp -d)
 cd $TEMPDIR
 
-convert $fullfilename $options_density
+go $fullfilename $options_density
 
 cd $wherewasi
 
diff --git a/obj-to-tri b/obj-to-tri
--- a/obj-to-tri
+++ b/obj-to-tri
@@ -2,97 +2,110 @@
 
 # Given an obj file, samples it to get it as a high-quality CSV.
 
-export readonly name=$( basename $0 )
+export readonly name=$(basename $0)
 
-source $( type -p comma-application-util ) || (error "comma not installed")
-function errcho { (>&2 echo "$name: $1") }
-function error
-{
-    errcho "error: $1"
-    exit 1
+source $(type -p comma-application-util) || (error "comma not installed")
+function errcho() { (echo >&2 "$name: $1"); }
+function error() {
+	errcho "error: $1"
+	exit 1
 }
 
 function convert() {
 	OBJ=$1
 	# TODO handle "g" fields as well
 
-	cat $OBJ | grep "^v" > verts.csv
-	cat $OBJ | grep '^v' | sed 's/v //' | tr ' ' ',' | csv-to-bin 3d | csv-paste  "-;binary=3d" line-number | csv-eval --binary=3d,ui --fields=,,,i "i=i+1" > vertices.bin
+	cat $OBJ | grep "^v" >verts.csv
+	cat $OBJ | grep '^v' | sed 's/v //' | tr ' ' ',' | csv-to-bin 3d | csv-paste "-;binary=3d" line-number | csv-eval --binary=3d,ui --fields=,,,i "i=i+1" >vertices.bin
 
-	if [[ `cat $OBJ | grep "^g"` ]]
-	then
+	if [[ $(cat $OBJ | grep "^g") ]]; then
 
 		gLines=$(cat $OBJ | grep "^g" -n | sed 's/:g//' | sed -r 's/\s/:/g')
 		lines=$(cat $OBJ | wc -l)
 		id=$(cat $OBJ | grep "^g" -n | wc -l)
 
-		for group in `echo "$gLines"`
-		do
+		for group in $(echo "$gLines"); do
 			set=$(echo "$gLines" | grep $group -A 1 | tr '\n' ':' | sed 's/:$/\n/')
-			[[ $verbose ]] && echo $set >&2
 			start=$(echo $set | cut -d: -f1)
 			label=$(echo $set | cut -d: -f2)
-			[[ verbose ]] && echo "$n" >&2
 			e=$(echo $set | cut -d: -f3)
 			n=$(expr $lines - $start)
-			if [[ $e ]]
-			then
+			if [[ $e ]]; then
 				end=$(expr $e - 1)
 				d=$(expr $end - $start)
-				[[ $verbose ]] && echo "A" >&2
-				cat $OBJ | tail -$n | head -$d > $id.obj
+				cat $OBJ | tail -$n | head -$d >$id.obj
 			else
-				[[ $verbose ]] && echo "B" >&2
-				cat $OBJ | tail -$n > $id.obj
+				cat $OBJ | tail -$n >$id.obj
 			fi
 			id=$(expr $id - 1)
-			[[ $verbose ]] && echo "boo" >&2
 		done
-else 
-	cp $OBJ 0.obj
-fi
-[[ $verbose ]] && echo "second" >&2
-	for f in `ls *.obj`
-	do
-	i=$(echo $f | cut -d. -f1)
-	[[ $verbose ]] && echo $i >&2
-	# Turns quads into triangles by arbitrary splitting
-	# Turns triangles into quads, cause otherwise shit goes bad.
-	# I don't know how to do this right though, if the order is wrong then this doesn't work
-	# To make sure the shape is closed, I do all possible triangles; this will lead to oversampling, but the shape is at least closed.
-	cat $f | grep '^f' | sed 's/f //' | tr ' ' ',' | 
-	sed -r 's/^([^,])*,([^,]*),([^,]*),([^,]*)$/\1,\2,\3\n\1,\3,\4\n\1,\2,\4\n\2,\3,\4/' | 
-	csv-to-bin 3ui | 
-	csv-join --fields=id --binary=3ui "vertices.bin;binary=3d,ui;fields=,,,id" |
-	csv-join --fields=,id --binary=3ui,3d,ui "vertices.bin;binary=3d,ui;fields=,,,id" |
-	csv-join --fields=,,id --binary=3ui,3d,ui,3d,ui "vertices.bin;binary=3d,ui;fields=,,,id" |
-	csv-shuffle -b=3ui,3d,ui,3d,ui,3d,ui -f=a,b,c,xa,ya,za,,xb,yb,zb,,xc,yc,zc -o=xa,ya,za,xb,yb,zb,xc,yc,zc |
-	csv-paste "value=$i;binary=ui" "-;binary=9d"
-done
+	else
+		cp $OBJ 0.obj
+	fi
+	for f in $(ls *.obj); do
+		i=$(echo $f | cut -d. -f1)
+		[[ $verbose ]] && echo "Processing group $i" >&2
+		# Turns quads into triangles by arbitrary splitting
+		# Turns triangles into quads, cause otherwise shit goes bad.
+		# I don't know how to do this right though, if the order is wrong then this doesn't work
+		# To make sure the shape is closed, I do all possible triangles; this will lead to oversampling, but the shape is at least closed.
+		cat $f | grep '^f' | sed 's/f //' | tr ' ' ',' |
+			sed -r 's/^([^,]*),([^,]*),([^,]*),([^,]*)$/\1,\2,\3\n\1,\3,\4\n\1,\2,\4\n\2,\3,\4/' |
+			csv-to-bin 3ui |
+			csv-join --fields=id --binary=3ui "vertices.bin;binary=3d,ui;fields=,,,id" |
+			csv-join --fields=,id --binary=3ui,3d,ui "vertices.bin;binary=3d,ui;fields=,,,id" |
+			csv-join --fields=,,id --binary=3ui,3d,ui,3d,ui "vertices.bin;binary=3d,ui;fields=,,,id" |
+			csv-shuffle -b=3ui,3d,ui,3d,ui,3d,ui -f=a,b,c,xa,ya,za,,xb,yb,zb,,xc,yc,zc -o=xa,ya,za,xb,yb,zb,xc,yc,zc |
+			csv-paste "value=$i;binary=ui" "-;binary=9d"
+	done
 
 }
 
-function option-description
-{
-    cat <<eof
+function option-description() {
+	cat <<eof
 --verbose, -v; Output progress to stderr
 eof
 }
 
-function usage
-{
-    cat <<eof
+function usage() {
+	cat <<eof
 
 $name turns an obj file into a binary list of triangle coordinates in ui,9d format (the UI is ID if g is included, 0 otherwise)
 Also creates a temporary directory to store intermediate files.
 
+Currently only the simplest of OBJ files are supported - simple vertices, groups and faces (quads or tris) are accepted, but no curves, no textures, etc.
+
 usage: $name obj [options]
 
+Example:
+cube.obj:
+    v 0.000000 2.000000 2.000000
+    v 0.000000 0.000000 2.000000
+    v 2.000000 0.000000 2.000000
+    v 2.000000 2.000000 2.000000
+    v 0.000000 2.000000 0.000000
+    v 0.000000 0.000000 0.000000
+    v 2.000000 0.000000 0.000000
+    v 2.000000 2.000000 0.000000
+	g one
+    f 1 2 3 4
+	g two
+    f 8 7 6 5
+	g three
+    f 4 3 7 8
+	g four
+    f 5 1 4 8
+	g five
+    f 5 6 2 1
+	g six
+    f 2 6 7 3
+obj-to-tri cube.obj | view-points --binary=ui,9d --fields=id,corners --shape=triangle
+
 options:
-$( option-description  | sed 's/^/    /g' )
+$(option-description | sed 's/^/    /g')
 
 eof
-    exit 1
+	exit 1
 
 }
 
@@ -102,20 +115,19 @@ if [ "$1" = "-parallel" ]; then
 	exit $?
 fi
 
+if (($(comma_options_has --help $@) || $(comma_options_has -h $@))); then usage; fi
+options=$(option-description | comma-options-to-name-value "$@") || error "invalid command line options"
+comma_path_value_to_var --prefix="options" <<<"$options"
+eval "$(option-description | comma-options-to-name-value "$@" | comma_path_value_mangle)"
 
-if (( $( comma_options_has --help $@ ) || $( comma_options_has -h $@ ) )) ; then usage ; fi
-options=$( option-description | comma-options-to-name-value "$@" ) || error "invalid command line options"
-comma_path_value_to_var --prefix="options" <<< "$options"
-eval "$( option-description | comma-options-to-name-value "$@" | comma_path_value_mangle )"
-
-(( $( comma_options_has --verbose "$@" ) )) && export readonly verbose=true
+(($(comma_options_has --verbose "$@"))) && export readonly verbose=true
 
 # set -e # Kill if anything errors out; we don't want it to run everything on bad datasets
 
-wherewasi=`pwd`
-fullfilename=`readlink -f $1`
+wherewasi=$(pwd)
+fullfilename=$(readlink -f $1)
 # export TEMPDIR=`mktemp -d`
-export TEMPDIR=`mktemp -d`
+export TEMPDIR=$(mktemp -d)
 cd $TEMPDIR
 
 [[ $verbose ]] && echo "Created $TEMPDIR" >&2
